In [1]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
data = pandas.read_csv('1.02.+Multiple+linear+regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [3]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Creating Multiple Linear Regression

### Declare dependent and independent variables

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Linear Regression itself

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

### Calculating R-Squared

In [8]:
reg.score(x,y)

0.4066811952814283

### Formula for Adjusted R-squared

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [9]:
x.shape #tuple of (n,p)

(84, 2)

In [10]:
r2 = reg.score(x,y)
n = x.shape[0] # number of observations
p = x.shape[1] # number of predictors
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### Feature Selection

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression(x,y) #array([7.19951844e-11, 6.76291372e-01])) => p-values
                  #(array([56.04804786,  0.17558437]) => F-statistics

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [13]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

### Rounding off

In [14]:
p_values.round(3) #to 3 decimal places

array([0.   , 0.676])

### Creating a summary table

In [15]:
# reg_summary = pandas.DataFrame(data=['SAT','Rand 1,2,3'],columns=['Features'])
#OR
reg_summary = pandas.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [16]:
reg_summary['Coefficients']=reg.coef_
reg_summary['p-values']=p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

### Standardization

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler() #will be used to subtract the mean and divide by the standard deviation

In [19]:
scaler.fit(x) #calculates and stores the mean and standard deviation of each feature

StandardScaler()

##### StandardScaler.transform(x) transforms the unscaled inputs using the information contained in the scaler object (feature-wise)

In [20]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

### Regression with scaled features

In [21]:
reg = LinearRegression()
reg.fit(x_scaled,y)
print(reg.fit(x_scaled,y))

LinearRegression()


In [24]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [25]:
reg.intercept_

3.330238095238095

### Creating a summary table

In [32]:
# reg_summary = pandas.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary = pandas.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1] #Weights is the machine learning word for coefficients, the bigger the weight the bigger the impact
reg_summary
#The machine learning word for intercept is bias

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030