In [1]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
data = pandas.read_csv('1.02.+Multiple+linear+regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [3]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Creating Multiple Linear Regression

### Declare dependent and independent variables

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

### Linear Regression itself

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

### Calculating R-Squared

In [8]:
reg.score(x,y)

0.4066811952814283

### Formula for Adjusted R-squared

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [9]:
x.shape #tuple of (n,p)

(84, 2)

In [10]:
r2 = reg.score(x,y)
n = x.shape[0] # number of observations
p = x.shape[1] # number of predictors
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### Feature Selection

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression(x,y) #array([7.19951844e-11, 6.76291372e-01])) => p-values
                  #(array([56.04804786,  0.17558437]) => F-statistics

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [13]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

### Rounding off

In [14]:
p_values.round(3) #to 3 decimal places

array([0.   , 0.676])

### Creating a summary table

In [15]:
# reg_summary = pandas.DataFrame(data=['SAT','Rand 1,2,3'],columns=['Features'])
#OR
reg_summary = pandas.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [16]:
reg_summary['Coefficients']=reg.coef_
reg_summary['p-values']=p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

### Standardization

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler() #will be used to subtract the mean and divide by the standard deviation

In [19]:
scaler.fit(x) #calculates and stores the mean and standard deviation of each feature

StandardScaler()

##### StandardScaler.transform(x) transforms the unscaled inputs using the information contained in the scaler object (feature-wise)

In [20]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

### Regression with scaled features

In [21]:
reg = LinearRegression()
reg.fit(x_scaled,y)
print(reg.fit(x_scaled,y))

LinearRegression()


In [22]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [23]:
reg.intercept_

3.330238095238095

### Creating a summary table

In [24]:
# reg_summary = pandas.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary = pandas.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1] #Weights is the machine learning word for coefficients, the bigger the weight the bigger the impact
reg_summary
#The machine learning word for intercept is bias

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### Making predictions with standardized coefficients (weights)

In [25]:
new_data = pandas.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [26]:
reg.predict(new_data)

/usr/local/lib64/python3.11/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [27]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [28]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

### What if we remove the 'Random 1,2,3' variable

In [29]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [30]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1)) #almost the same as in line29

array([3.08970998, 3.25527879])

### Train Test Split

In [32]:
import numpy
from sklearn.model_selection import train_test_split

### Generate data we are going to split

In [33]:
a = numpy.arange(1,101) #numpy arange([start,]stop,[step]) => returns evenly spaced values within a given interval. By default the output is an ndarray
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [34]:
b = numpy.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Split Data

In [36]:
# train_test_split(x) splits arrays or matrices into random train and train subsets
# the first array in the train_test_split(a) is the training array, the second one is the testing array
train_test_split(a)

[array([ 68,  49, 100,  71,  76,  53,  96,  77,  98,  63,  90,  65,  62,
         20,  97,  60,  45,  51,  13,  80,  95,  40,  92,  84,   5,  89,
         73,   8,  33,  11,  14,  70,  57,  82,  37,  83,  17,   4,   6,
         44,  36,  88,  64,  55,  30,  21,  10,  18,  74,  29,  87,  85,
         28,  48,  41,  67,  75,  26,  86,  35,  23,   1,  54,  79,  19,
         32,  99,   2,  61,  56,  81,  34,  42,  39,  27]),
 array([38, 31, 59,  7, 58,  3, 22,  9, 91, 43, 46, 93, 72, 66, 52, 78, 24,
        94, 25, 16, 69, 15, 12, 50, 47])]

In [60]:
# a_train, a_test = train_test_split(a)
# To achieve an 80, 20 split, we include the argument test_size=0.2
# a_train, a_test = train_test_split(a, test_size=0.2,shuffle=False) => To have an unshuffled split
# a_train, a_test = train_test_split(a, test_size=0.2)
a_train, a_test = train_test_split(a, test_size=0.2)

### Explore the result

In [56]:
a_train.shape, a_test.shape

((80,), (20,))

### The respective arrays

In [58]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [59]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])